spring:
  application:
    name: demo-provider

eureka:
  instance:
    prefer-ip-address: true # 注册服务的时候使用服务的ip地址
  client:
    service-url:
      defaultZone: http://localhost:8082/eureka/,http://localhost:8083/eureka/ # 注册中心的地址
